CREATE TABLE [dbo].[TableNames]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[TableName] VARCHAR(255) NOT NULL,
	[Database] VARCHAR(255) NULL,
	[CreatedDate] DATETIME2(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
